CREATE DATABASE IF NOT EXISTS cfms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE cfms;

CREATE TABLE IF NOT EXISTS admins (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS students (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  registration_no VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  dob DATE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  semester TINYINT UNSIGNED NOT NULL,
  section ENUM('A','B','C') NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (semester BETWEEN 1 AND 8)
) ENGINE=InnoDB;

CREATE INDEX idx_students_sem_sec ON students (semester, section);

CREATE TABLE IF NOT EXISTS faculty (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  faculty_code VARCHAR(30) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  department VARCHAR(120) NOT NULL,
  designation VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(30) NOT NULL UNIQUE,
  course_name VARCHAR(150) NOT NULL,
  short_name VARCHAR(80) NOT NULL,
  credits DECIMAL(3,1) NOT NULL,
  semester TINYINT UNSIGNED NOT NULL,
  subject_type ENUM('core','elective') NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (semester BETWEEN 1 AND 8)
) ENGINE=InnoDB;

CREATE INDEX idx_courses_sem_type ON courses (semester, subject_type);

CREATE TABLE IF NOT EXISTS forms (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  form_title VARCHAR(180) NOT NULL,
  feedback_for ENUM('faculty','course') NOT NULL DEFAULT 'faculty',
  subject_type ENUM('core','elective') NOT NULL,
  academic_year VARCHAR(7) NOT NULL,
  semester TINYINT UNSIGNED NOT NULL,
  section ENUM('A','B','C','MIXED') NULL,
  feedback_period ENUM('mid-semester','end-semester') NOT NULL,
  course_id BIGINT UNSIGNED NOT NULL,
  faculty_id BIGINT UNSIGNED NOT NULL,
  published_at_utc DATETIME NOT NULL,
  closes_at_utc DATETIME NOT NULL,
  status_override ENUM('active','closed') DEFAULT NULL,
  created_by_admin_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CHECK (semester BETWEEN 1 AND 8),
  CHECK (academic_year REGEXP '^[0-9]{4}-[0-9]{2}$'),
  CONSTRAINT chk_forms_section_by_type CHECK (
    (subject_type = 'core' AND section IS NOT NULL) OR
    (subject_type = 'elective' AND section IS NULL)
  ),
  CONSTRAINT fk_forms_course FOREIGN KEY (course_id) REFERENCES courses(id),
  CONSTRAINT fk_forms_faculty FOREIGN KEY (faculty_id) REFERENCES faculty(id),
  CONSTRAINT fk_forms_admin FOREIGN KEY (created_by_admin_id) REFERENCES admins(id)
) ENGINE=InnoDB;

CREATE INDEX idx_forms_ordered ON forms (academic_year, semester, section, subject_type);
CREATE INDEX idx_forms_created_at ON forms (created_at);

CREATE TABLE IF NOT EXISTS form_student_targets (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  form_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_form_student_target (form_id, student_id),
  CONSTRAINT fk_targets_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE,
  CONSTRAINT fk_targets_student FOREIGN KEY (student_id) REFERENCES students(id)
) ENGINE=InnoDB;

CREATE INDEX idx_targets_student_form ON form_student_targets (student_id, form_id);

CREATE TABLE IF NOT EXISTS feedback_responses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  form_id BIGINT UNSIGNED NOT NULL,
  student_id BIGINT UNSIGNED NOT NULL,
  q1 TINYINT UNSIGNED NOT NULL,
  q2 TINYINT UNSIGNED NOT NULL,
  q3 TINYINT UNSIGNED NOT NULL,
  q4 TINYINT UNSIGNED NOT NULL,
  q5 TINYINT UNSIGNED NOT NULL,
  q6 TINYINT UNSIGNED NOT NULL,
  q7 TINYINT UNSIGNED NOT NULL,
  q8 TINYINT UNSIGNED NOT NULL,
  q9 TINYINT UNSIGNED NOT NULL,
  q10 TINYINT UNSIGNED NOT NULL,
  q11 TINYINT UNSIGNED NOT NULL,
  q12 VARCHAR(100) NOT NULL,
  q13 VARCHAR(100) NOT NULL,
  q14 VARCHAR(100) NOT NULL,
  q15 TINYINT UNSIGNED NOT NULL,
  q16 TINYINT UNSIGNED NOT NULL,
  q17 TINYINT UNSIGNED NOT NULL,
  q18 TINYINT UNSIGNED NOT NULL,
  q19 TINYINT UNSIGNED NOT NULL,
  q20 TINYINT UNSIGNED NOT NULL,
  q21 TINYINT UNSIGNED NOT NULL,
  q22 TINYINT UNSIGNED NOT NULL,
  q23 TINYINT UNSIGNED NOT NULL,
  q24 TINYINT UNSIGNED NOT NULL,
  q25 TINYINT UNSIGNED NOT NULL,
  q26 TINYINT UNSIGNED NOT NULL,
  q27 TINYINT UNSIGNED NOT NULL,
  q28 TINYINT UNSIGNED NOT NULL,
  q29 TINYINT UNSIGNED NOT NULL,
  q30 TINYINT UNSIGNED NOT NULL,
  q31 TINYINT UNSIGNED NOT NULL,
  q32 TINYINT UNSIGNED NOT NULL,
  q33 VARCHAR(100) NOT NULL,
  q34 VARCHAR(100) NOT NULL,
  q35 VARCHAR(100) NOT NULL,
  submitted_at_utc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_feedback_once (form_id, student_id),
  CONSTRAINT fk_feedback_form FOREIGN KEY (form_id) REFERENCES forms(id) ON DELETE CASCADE,
  CONSTRAINT fk_feedback_student FOREIGN KEY (student_id) REFERENCES students(id),
  CONSTRAINT chk_q1 CHECK (q1 BETWEEN 1 AND 5),
  CONSTRAINT chk_q2 CHECK (q2 BETWEEN 1 AND 5),
  CONSTRAINT chk_q3 CHECK (q3 BETWEEN 1 AND 5),
  CONSTRAINT chk_q4 CHECK (q4 BETWEEN 1 AND 5),
  CONSTRAINT chk_q5 CHECK (q5 BETWEEN 1 AND 5),
  CONSTRAINT chk_q6 CHECK (q6 BETWEEN 1 AND 5),
  CONSTRAINT chk_q7 CHECK (q7 BETWEEN 1 AND 5),
  CONSTRAINT chk_q8 CHECK (q8 BETWEEN 1 AND 5),
  CONSTRAINT chk_q9 CHECK (q9 BETWEEN 1 AND 5),
  CONSTRAINT chk_q10 CHECK (q10 BETWEEN 1 AND 5),
  CONSTRAINT chk_q11 CHECK (q11 BETWEEN 1 AND 5),
  CONSTRAINT chk_q15 CHECK (q15 BETWEEN 1 AND 5),
  CONSTRAINT chk_q16 CHECK (q16 BETWEEN 1 AND 5),
  CONSTRAINT chk_q17 CHECK (q17 BETWEEN 1 AND 5),
  CONSTRAINT chk_q18 CHECK (q18 BETWEEN 1 AND 5),
  CONSTRAINT chk_q19 CHECK (q19 BETWEEN 1 AND 5),
  CONSTRAINT chk_q20 CHECK (q20 BETWEEN 1 AND 5),
  CONSTRAINT chk_q21 CHECK (q21 BETWEEN 1 AND 5),
  CONSTRAINT chk_q22 CHECK (q22 BETWEEN 1 AND 5),
  CONSTRAINT chk_q23 CHECK (q23 BETWEEN 1 AND 5),
  CONSTRAINT chk_q24 CHECK (q24 BETWEEN 1 AND 5),
  CONSTRAINT chk_q25 CHECK (q25 BETWEEN 1 AND 5),
  CONSTRAINT chk_q26 CHECK (q26 BETWEEN 1 AND 5),
  CONSTRAINT chk_q27 CHECK (q27 BETWEEN 1 AND 5),
  CONSTRAINT chk_q28 CHECK (q28 BETWEEN 1 AND 5),
  CONSTRAINT chk_q29 CHECK (q29 BETWEEN 1 AND 5),
  CONSTRAINT chk_q30 CHECK (q30 BETWEEN 1 AND 5),
  CONSTRAINT chk_q31 CHECK (q31 BETWEEN 1 AND 5),
  CONSTRAINT chk_q32 CHECK (q32 BETWEEN 1 AND 5)
) ENGINE=InnoDB;

CREATE INDEX idx_feedback_form ON feedback_responses (form_id);
CREATE INDEX idx_feedback_student ON feedback_responses (student_id);

CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(128) PRIMARY KEY,
  user_type ENUM('student','admin') NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  data_json JSON NULL,
  expires_at_utc DATETIME NOT NULL,
  created_at_utc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE INDEX idx_sessions_expires ON sessions (expires_at_utc);
CREATE INDEX idx_sessions_user ON sessions (user_type, user_id);
